version: '3.7'

services:
  web:
    image: wger/devel:latest
    command: bash -c "/home/wger/entrypoint.sh"
    volumes:
      - 'wger:/home/wger/src'
    ports:
      - 8000:8000
    env_file:
      - ./dev.env
    depends_on:
      - db
      - cache

  db:
    image: postgres:12.0-alpine
    volumes:
      - wger-postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=wger
      - POSTGRES_DB=wger

  cache:
    restart: always
    image: redis:latest
    expose:
      - 6379

volumes:
  wger-postgres-data:
  wger:
